Make robust to changing number of whitespace between data column entries
terencebarrett/rededge-api pull request #2
Opened 2022-04-01 15:45 UTC by terencebarrett

Resolves Issue #1

2022-04-01 17:46 UTC, terencebarrett commented
This is still only a small step toward making this script more robust - for long-term production use there is more work to do. 

Reading/writing using Pandas dataframes (replacing use of the `csv` module) will probably be useful in future.

2022-04-07 19:39 UTC, azylka approved these changes

2022-04-07 19:47 UTC, calekochenour requested changes

2022-04-07 19:47 UTC, calekochenour commented on examples/gps_image_insert.py
> +                    data_list = [data for data in row if data != '']
Looks good.

2022-04-07 19:47 UTC, calekochenour commented on examples/gps_image_insert.py
> +                    longitude = data_list[3]
Test.

2022-04-07 19:51 UTC, calekochenour approved these changes

2022-04-07 19:52 UTC, merged